### ISSUE TITLE
Call for Testing: No more ExceptT

### ISSUE THREAD

**Issue by valpackett** [myfreeweb/magicbane#10]
Magicbane git master is now [ExceptT-free](https://www.parsonsmatt.org/2017/06/21/exceptional_servant_handling.html). (More explanation in the 209cfbf8484c2ef5b5b20eb4a54b728ef45b547f commit message.) The new method of throwing errors is `throwIO`.

Please test your applications!

/cc @tejon

**Comment by akhra** [comment]
Building with `lts-10.9` (old `conduit`) I get the following errors:
```
    /library/Magicbane/HTTPClient.hs:68:79: error:
        Not in scope: type constructor or class ‘ConduitT’
        Perhaps you meant one of these:
          ‘Conduit’ (imported from Data.Conduit),
          ‘ConduitM’ (imported from Data.Conduit)
       |
    68 | performWithFn ∷ (MonadHTTP ψ μ, MonadCatch μ) ⇒ (ConduitM ι ByteString μ () → ConduitT () Void μ ρ) → Request → ExceptT Text μ (Response ρ)
       |                                                                               ^^^^^^^^
    
    /library/Magicbane/HTTPClient.hs:68:91: error:
        Not in scope: type constructor or class ‘Void’
       |
    68 | performWithFn ∷ (MonadHTTP ψ μ, MonadCatch μ) ⇒ (ConduitM ι ByteString μ () → ConduitT () Void μ ρ) → Request → ExceptT Text μ (Response ρ)
       |                                                                                           ^^^^
```
Not sure whether this is avoidable without a whole bunch of CPP, though.

**Comment by valpackett** [comment]
I'm probably not going to support old conduit…

**Comment by akhra** [comment]
> I'm probably not going to support old conduit…

Good enough for me, just making a thorough report. :)

On the positive side: switching `throwError` to `throwIO` fixed my build, didn't even need to change any signatures.
