### ISSUE TITLE
Conflicting exports for 'host' when building against latest wai-cli

### ISSUE THREAD

**Issue by tocklime** [myfreeweb/magicbane#24]
I'm trying to build my project which references magicbane-0.4.0, but with extra-deps:

```stack.yaml
extra-deps:
- github: myfreeweb/wai-cli
  commit: 6cdd4d03a538a16b7f94ea9fca79bdab0d103d35
```

in order to compile against latest wai-cli.

The stack build of magicbane is failing with:

```
    /tmp/stack4749/magicbane-0.4.0/library/Magicbane.hs:13:3: error:
        Conflicting exports for ‘host’:
           ‘module X’ exports ‘X.host’
             imported from ‘Network.Wai.Cli’ at library/Magicbane.hs:32:1-51
           ‘module X’ exports ‘X.host’
             imported from ‘Magicbane.HTTPClient’ at library/Magicbane.hs:39:1-42
             (and originally defined in ‘http-client-0.5.14:Network.HTTP.Client.Types’)
```
Does it just need a hiding(host) in https://github.com/myfreeweb/magicbane/blob/master/library/Magicbane.hs#L32 ? Or am I trying to do something which isn't expected to work?

(the reason I'm trying to do this is I'm looking to put together a pull request for wai-cli to allow building on windows)

**Comment by valpackett** [comment]
Thanks for bringing this to my attention —

> Does it just need a hiding(host)

that would work, but that's really silly. wai-cli shouldn't pollute the namespace with these names. I just released wai-cli 0.2.0 with them renamed.
