### ISSUE TITLE
Suggest changing license from UNLICENSE/public domain to BSD3

### ISSUE THREAD

**Issue by bitemyapp** [myfreeweb/magicbane#3]
This is just a friendly suggestion meant to help you achieve your own goals.

Some pointers to this end:

- https://www.gnu.org/licenses/gpl-faq.en.html#AssignCopyright

- Some jurisdictions consider public domain IP, even from different nation-states, to be State property and charge license fees for using public domain IP

- https://tldrlegal.com/license/bsd-3-clause-license-(revised)#fulltext

Particularly,

>Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

**Comment by valpackett** [comment]
No.

**Comment by bitemyapp** [comment]
Fair 👍
