### ISSUE TITLE
Poor type interaction with :<|>

### ISSUE THREAD

**Issue by akhra** [myfreeweb/magicbane#6]
Given:
```
type EntitiesAPI = "entities"
  :> Capture "objtype" Object
  :> Capture "uuid" IdDynamic
  :> EntityAPI

type EntityAPI
  =    Get '[JSON] APIResult
  :<|> Capture "childtype" Text
       :> Get '[JSON] APIResult

entitiesHandler obj uuid = getEntityAPI bare :<|> const (getEntityAPI full)
  where
    bare = EntityAPIRequest obj uuid False
    full = EntityAPIRequest obj uuid True

getEntityAPI x = _
```

With Servant, I have the following types:
```
entitiesHandler :: Server EntitiesAPI
getEntityAPI :: EntityAPIRequest -> Handler APIResult
```

With Magicbane, they become:
```
entitiesHandler :: Object -> IdDynamic -> MyApp APIResult :<|> (Text -> MyApp APIResult)
getEntityAPI :: EntityAPIRequest -> MyApp APIResult
```

The latter may not be a problem (I haven't directly hit an issue with it, but the change seems notable). The former, however, has some nasty implications. This will eventually be only one part of the API. I also have:
```
type MyAPI
  =    EntitiesAPI
  -- more here later

api
  =    entitiesHandler
  -- More here later
```

The comparative types of `api` are:
```
api :: Server MyAPI
-- vs. --
api :: Object -> IdDynamic -> MyApp APIResult :<|> (Text -> MyApp APIResult)
```

That looks like it's going to become a nightmare as I fill out the API. I noticed that the examples mostly just don't have type annotations, but I'm working in a team environment and they're not something I want to give up. Is there a path forward from here?

**Comment by valpackett** [comment]
Uh, I'm not sure how you went from `Server EntitiesAPI` to `Object -> IdDynamic -> MyApp APIResult :<|> (Text -> MyApp APIResult)`. (Haskell inferred that for you? It's not *that* smart I guess :D)

Just like you have `Server` without transformers, you have `ServerT` with them:

https://github.com/myfreeweb/sweetroll/blob/be0cef7537c2fd76ec8214dd7108e4f25ada7afd/sweetroll-be/library/Sweetroll/App.hs#L16-L19

I guess this should be documented somewhere here, yeah.

(also wow, this little library is used in a team environment! nice)

**Comment by akhra** [comment]
> `ServerT`

Well now I just feel silly. :) Yep, that fixes everything.

> (also wow, this little library is used in a team environment! nice)

Not a _big_ team, but yeah! It implements a bunch of ideas we already planned to use, while not forcing anything we really want to avoid. Seems like a win all around, and by coincidence it showed up on our radar just as we were starting this project.

**Comment by akhra** [comment]
(By the way yes, those are the types GHC inferred when I gave it holes to fill.)
