### ISSUE TITLE
(discussion) Keeping an eye on RIO?

### ISSUE THREAD

**Issue by akhra** [myfreeweb/magicbane#7]
Magicbane asserts Snoyman's `classy-prelude`. With the recent reveal of [`RIO`](https://github.com/commercialhaskell/rio), and Snoyman on board that project, it may be worth considering the benefits/logistics of moving to it.

**Comment by akhra** [comment]
Anecdotally, in testing the adjustment to our (admittedly still small) current codebase to each of Classy and RIO in isolation, the latter required less adjustment.

Would it be worthwhile to explore the option with a fork? (Should that fork be called Snickersnee, or Grayswandir? Only the most important questions, here.)

**Comment by valpackett** [comment]
Yeah, I saw RIO on various news link sites, it looks interesting I guess.

Magicbane was extracted from [a Classy based application](https://github.com/myfreeweb/sweetroll/tree/master/sweetroll-be), but there's no actual reason to use one prelude over another here…

What about the option of not using custom preludes here? Honestly the only reason was that `import Magicbane` is the one and only import in the little demos, but that's silly. I'd totally accept a PR that replaces Classy with the regular base Prelude :)

**Comment by akhra** [comment]
That'd just be a matter of not re-exporting it, right? And fixing the examples.

**Comment by akhra** [comment]
I guess that would still force the dependency for people using another prelude. Still, it opens options and is a clean&easy first step.

**Comment by valpackett** [comment]
No, I mean completely removing it

**Comment by akhra** [comment]
Fair enough, shouldn't be too much more work.

**Comment by akhra** [comment]
99.9% done, `examples/tiny.hs` runs; `examples/larger.hs` is choking on:
```
No instance for (exceptions-0.8.3:Control.Monad.Catch.MonadMask
                         (MagicbaneApp LargeAppCtx))
        arising from a use of ‘timed’
```
Do you happen to have an insight on where that instance was coming from previously?

**Comment by akhra** [comment]
For reference, [here's where I'm at](https://github.com/tejon/magicbane). The only thing that seems to be broken is the `timed` call, both in `larger.hs` and the second readme example. It doesn't seem to be due to the absence of `ClassyPrelude` tho, as I went ahead and imported it for the examples (and moved it to "recommended" in readme) so basically everything it provides should be there. I may have broken something in `Magicbane.App`?

**Comment by akhra** [comment]
Strike that -- I just made a fresh clone of your repository and got the same errors. Not my fault! :P (Or, if my fault, something in tooling/environment, not code.) Gonna open the PR, further discussion there.
